fix sql bug (vibe-kanban d884aa6f)
2026-01-20T07:45:44.980730Z  INFO sea\_orm\_migration::migrator: Applying migration 'm003\_extend\_tasks'

thread 'main' (270509) panicked at /home/isomo/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-4dc01642fd091eda/sea-query-0.32.7/src/backend/sqlite/table.rs:66:13:

Sqlite doesn't support multiple alter options