db migrations had error, use orm lib replace (vibe-kanban 3b6aced2)
Connecting to database: sqlite://.ikanban/data/db.sqlite

Error: error returned from database: (code: 1) duplicate column name: repo\_path

Caused by:

    (code: 1) duplicate column name: repo\_path

make: \*\*\* [Makefile:34: run-server] Error 1